tap "1password/tap"
tap "buo/cask-upgrade"
tap "goreleaser/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "openresty/brew"
tap "osx-cross/avr"
tap "shopify/shopify"
tap "vitorgalvao/tiny-scripts"
brew "ack"
brew "act"
brew "adns"
brew "bzip2"
brew "openssl@1.1", link: true
brew "apache-arrow"
brew "astyle"
brew "gettext"
brew "glib"
brew "atk"
brew "autoconf"
brew "automake"
brew "readline", link: true
brew "docutils"
brew "awscli"
brew "gdbm"
brew "python@3.10"
brew "azure-cli"
brew "icu4c"
brew "harfbuzz"
brew "bfg"
brew "bison"
brew "cabal-install"
brew "coreutils"
brew "unbound"
brew "gnutls"
brew "jansson"
brew "emacs"
brew "cask"
brew "clang-format"
brew "cmake"
brew "cowsay"
brew "libssh2"
brew "openldap"
brew "curl"
brew "docker-compose"
brew "docker-machine"
brew "docx2txt"
brew "dos2unix"
brew "dpkg"
brew "folly"
brew "edencommon"
brew "exercism"
brew "libsodium"
brew "fizz"
brew "wangle"
brew "fbthrift"
brew "fb303"
brew "lame"
brew "libass"
brew "pango"
brew "tesseract"
brew "ffmpeg"
brew "gcc"
brew "flex"
brew "portaudio"
brew "fluid-synth"
brew "freetds"
brew "fzf"
brew "geos"
brew "hdf5"
brew "krb5"
brew "libxml2"
brew "libdap"
brew "libpq"
brew "numpy"
brew "poppler"
brew "gdal"
brew "gdk-pixbuf"
brew "geoip"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-lfs"
brew "gsettings-desktop-schemas"
brew "glib-networking"
brew "go"
brew "glide"
brew "gnupg"
brew "gnuplot"
brew "pkg-config"
brew "gobject-introspection"
brew "gox"
brew "gradle"
brew "librsvg"
brew "graphviz"
brew "grc"
brew "groff"
brew "gtk+3"
brew "libsoup"
brew "py3cairo"
brew "pygobject3"
brew "libnice"
brew "handbrake", link: false
brew "htop"
brew "hub"
brew "hugo"
brew "influxdb"
brew "influxdb-cli"
brew "intltool"
brew "iperf"
brew "jemalloc"
brew "jq"
brew "lcov"
brew "libdvdcss"
brew "libffi", link: true
brew "libproxy"
brew "libxcrypt"
brew "libyaml"
brew "llvm"
brew "logrotate", restart_service: true
brew "mas"
brew "media-info"
brew "memcached", restart_service: true
brew "minikube"
brew "qt"
brew "mkvtoolnix"
brew "zlib"
brew "mysql"
brew "nghttp2"
brew "nginx"
brew "nmap"
brew "node-build"
brew "nodenv"
brew "overmind"
brew "p7zip"
brew "pandoc"
brew "postgresql@14", restart_service: true
brew "pidof"
brew "pmd"
brew "poppler-qt5"
brew "postgis"
brew "potrace"
brew "pulseaudio"
brew "pure"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python@3.9"
brew "ragel"
brew "ruby-build"
brew "rbenv"
brew "rcm"
brew "redis", restart_service: true
brew "ruby-install"
brew "s3cmd"
brew "scipy"
brew "shadowenv"
brew "socat"
brew "softhsm"
brew "swiftformat"
brew "telnet"
brew "thefuck"
brew "the_silver_searcher"
brew "tree"
brew "vala"
brew "vips"
brew "watchman"
brew "wget"
brew "yarn"
brew "yt-dlp"
brew "zsh"
brew "zsh-completions"
brew "goreleaser/tap/goreleaser"
brew "vitorgalvao/tiny-scripts/cask-repair"
cask "1password"
cask "1password-cli"
cask "alt-tab"
cask "discord"
cask "docker"
cask "dotnet"
cask "dropbox"
cask "font-fira-code"
cask "google-chrome"
cask "google-cloud-sdk"
cask "graphiql"
cask "handbrake"
cask "insomnia"
cask "iterm"
cask "mullvadvpn"
cask "ngrok"
cask "sublime-text"
cask "thinkorswim"
cask "transmission"
cask "viscosity"
cask "visual-studio-code"
cask "vnc-viewer"
cask "xquartz"
cask "zoom"
mas "1Password for Safari", id: 1_569_813_296
mas "Amphetamine", id: 937_984_704
mas "Cyberduck", id: 409_222_199
mas "Developer", id: 640_199_958
mas "GIF Brewery 3", id: 1_081_413_713
mas "Hex Fiend", id: 1_342_896_380
mas "iMovie", id: 408_981_434
mas "Instapaper Save", id: 1_481_302_432
mas "Keynote", id: 409_183_694
mas "Kindle", id: 405_399_194
mas "Microsoft Excel", id: 462_058_435
mas "Microsoft Word", id: 462_054_704
mas "Moom", id: 419_330_170
mas "Numbers", id: 409_203_825
mas "Pages", id: 409_201_541
mas "Pixelmator Pro", id: 1_289_583_905
mas "Scrivener", id: 1_310_686_187
mas "Simple Comic", id: 1_497_435_571
mas "Slack", id: 803_453_959
mas "Snagit 2022", id: 1_564_091_330
mas "Textual IRC Client", id: 1_262_957_439
mas "Userscripts", id: 1_463_298_887
mas "WhatsApp", id: 1_147_396_723
mas "Xcode", id: 497_799_835
